---
title: ""
author: "Ling"
date: "Update : `r format(Sys.time(), '%Y / %m / %d - %H:%M')`"
output:
  rmdformats::readthedown:
     code_folding: hide
     number_sections: FALSE
     toc_float:
       collapsed: FALSE
---

```{r setup, include=FALSE}
library(devtools)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(data.table)
library(rmdformats)
library(knitr)
library(DT)
library(kableExtra)
library(highcharter)
library(RColorBrewer)
library(lubridate)
library(stringr)
library(readr)
library(readxl)
library(ggplot2)
library(GGally)
library(caret)

knitr::opts_chunk$set(echo=TRUE,
                       cache=FALSE,
                       prompt=FALSE,
                       tidy=FALSE,
                       comment=NA,
                       message=FALSE,
                       warning=FALSE,
                      fig.align = 'center')

dt <- function(data){
  data %>% 
    datatable(extensions = 'Buttons', filter = 'top',
              options = list(dom = 'Bfrtip', scrollX = TRUE,
                             buttons = c('copy', 'csv', 'excel')), rownames = FALSE)
}
```

---

## Dataset {.tabset}

### Read training and testing data
```{r}
train <- fread("data/Tbrain-dataset-0510/train.csv")
test <- fread("data/Tbrain-dataset-0510/test.csv")
# train %>% head(10) %>% View
train %>% head(10) %>% dt
```


#### city name mapping
```{r}
tw_district <- read_excel("data/city_mapping.xlsx", sheet = 2) %>% select(-5)
train %>% 
  select(1:33, 235) %>% 
  left_join(tw_district) %>% 
  group_by(city, town, city_name, district_name) %>% 
  summarise(n = n()) %>% View
```


---

#### unit price

```{r}
train %>% 
  select(1:33, 235) %>% 
  mutate(building_age = (txn_dt - building_complete_dt)/365,
         unit_price = (total_price-ifelse(is.na(parking_price),0,parking_price))/(land_area+building_area-ifelse(is.na(parking_area),0,parking_area))) %>% 
  left_join(tw_district) %>% 
  group_by(city, town, city_name, district_name) %>% 
  summarise(n = n(),
            avg_unit_price = mean(unit_price, na.rm = TRUE),
            med_unit_price = median(unit_price, na.rm = TRUE)) %>% 
  arrange(desc(med_unit_price)) %>% dt
```

---

```{r}
train %>% 
  select(1:33, 235) %>% 
  left_join(tw_district) %>% 
  mutate(txn_dt_original = round(txn_dt/365, 2) + 1962.63,
         txn_dt_year_original = floor(round(txn_dt/365, 2) + 1962.63),
         txn_dt_month_original = round((txn_dt_original - floor(txn_dt_original))*12, 0),
         building_complete_dt_original = round(building_complete_dt/365, 2) + 1962.63,
         building_complete_dt_year_original = floor(round(building_complete_dt/365, 2) + 1962.63),
         building_complete_dt_month_original = round((building_complete_dt_original - floor(building_complete_dt_original))*12, 0),
      house_age_original = round((txn_dt - building_complete_dt)/365, 2),
      unit_price = (total_price-ifelse(is.na(parking_price),0,parking_price))/
        (land_area+building_area-ifelse(is.na(parking_area),0,parking_area))) %>% 
  mutate(txn_dt_month_original = ifelse(txn_dt_month_original == 0, 1, txn_dt_month_original),
         building_complete_dt_month_original = ifelse(building_complete_dt_month_original == 0, 1,
                                                      building_complete_dt_month_original)) %>% 
  select(34, 44, everything()) -> train_tb
  # arrange(txn_dt_original %>% desc()) %>% head() %>% View

set.seed(3456)
train_tb_index <- createDataPartition(train_tb$town, p = .8, 
                                      list = FALSE, 
                                      times = 1)
train_tb %>% 
  select(total_price, parking_price, total_floor, txn_floor, city_name, district_name, village, village_income_median,
         town_population_density, doc_rate, master_rate, bachelor_rate, jobschool_rate, highschool_rate,
         junior_rate, born_rate, divorce_rate, 
         building_complete_dt_year_original, building_complete_dt_month_original, house_age_original,
         lat, lon) -> train_tb_select

train_tb_train <- train_tb_select[train_tb_index,]
train_tb_test <- train_tb_select[-train_tb_index,]

train_tb_test %>% 
  distinct(city_name, district_name) %>% 
  inner_join(train_tb_train)  -> train_tb_train_filter

train_tb_train_filter %>% 
  distinct(city_name, district_name) %>% 
  inner_join(train_tb_test)  -> train_tb_test_filter
  
train_tb_train_filter %>%
  mutate(type = "train") %>%
  bind_rows(train_tb_test_filter %>% mutate(type = "test")) %>% 
  mutate(city_name = city_name %>% as.factor(),
         district_name = district_name %>% as.factor()) -> train_tb_test_filter_all

train_tb_test_filter_all %>% 
  filter(type == "train") %>% 
  select(-type) -> train_tb_train_filter

train_tb_test_filter_all %>% 
  filter(type == "test") %>% 
  select(-type)  -> train_tb_test_filter

train_tb_train_filter %>% 
  distinct(district_name) %>% nrow

train_tb_test_filter %>% 
  distinct(district_name) %>% nrow

levels(train_tb_train_filter$district_name)
levels(train_tb_test_filter$district_name)

```
---
```{r}
## Deal missing value ##
column_name <- NULL
for(i in 1:ncol(train_tb)){
  tmp <- ifelse(sum(is.na(train_tb %>% select(i))) != 0, colnames(train_tb %>% select(i)), "NA")
  column_name <- c(column_name, tmp)
}

# parking price, parking area(Add parking price to final result after predicted)
train_tb %>% 
  filter(!is.na(parking_price), !is.na(parking_area)) %>% 
  select(city_name, district_name, parking_way, parking_price, parking_area) %>% 
  mutate(unit_parking_price = parking_price /parking_area) %>% 
  group_by(city_name, district_name, parking_way) %>% View
  summarise(avg_unit_parking_price = mean(unit_parking_price, na.rm = T),
            sd_unit_parking_price = sd(unit_parking_price, na.rm = T),
            count = n()) %>% View
  
# txn_floor(NA fill 99, and create a column is total_bought_floors)
train_tb %>% 
  #select(city_name, district_name, total_price, unit_price, total_floor, txn_floor) %>% 
  mutate(txn_floor = ifelse(is.na(txn_floor), 99, txn_floor),
         total_bought_floors = ifelse(txn_floor == 99, total_floor, 1)) -> train_tb

# village_income_median
train_tb %>% 
  group_by(city_name, district_name, village, village_income_median) %>% 
  summarise(village_income_median_groupby = median(village_income_median, na.rm = T)) -> train_tb_village_income_median

train_tb %>% 
  group_by(city_name, district_name, village, village_income_median) %>% 
  summarise(count = n()) %>% 
  group_by(city_name, district_name, village, village_income_median) %>% 
  summarise(count = n()) %>% 
  filter(is.na(village_income_median)) %>% View
  

train_tb %>% 
  select(city_name, district_name, village, village_income_median) %>% 
  filter(is.na(village_income_median)) %>% View
  group_by(city_name, district_name, village) %>%
  mutate(village_income_median = ifelse(!is.na(village_income_median), village_income_median,
                                        median(village_income_median, na.rm = T))) %>% View


train_tb %>% 
  select(city_name, district_name, village, lat, lon, village_income_median) %>% 
  distinct() %>% 
  filter(city_name == "新北市", district_name == "土城區") %>% View

```
---

```{r}
test %>% 
  select(1:33) %>% 
  left_join(tw_district) %>% 
  mutate(txn_dt_original = round(txn_dt/365, 2) + 1962.63,
         txn_dt_year_original = floor(round(txn_dt/365, 2) + 1962.63),
         txn_dt_month_original = round((txn_dt_original - floor(txn_dt_original))*12, 0),
         building_complete_dt_original = round(building_complete_dt/365, 2) + 1962.63,
         building_complete_dt_year_original = floor(round(building_complete_dt/365, 2) + 1962.63),
         building_complete_dt_month_original = round((building_complete_dt_original - floor(building_complete_dt_original))*12, 0),
         house_age_original = round((txn_dt - building_complete_dt)/365, 2)
  ) %>% 
  mutate(txn_dt_month_original = ifelse(txn_dt_month_original == 0, 1, txn_dt_month_original),
         building_complete_dt_month_original = ifelse(building_complete_dt_month_original == 0, 1, building_complete_dt_month_original)) -> test_tb
```

---
```{r}
### training model
train_tb_train %>% 
  ggplot(aes(x = log(total_price))) +
  geom_density()

lm(log(total_price) ~ ., data = train_tb_train_filter[, -2]) -> training_result

predict(training_result, train_tb_test_filter) -> testing_result

train_tb_test_filter %>% 
  mutate(total_price_pred = lm(log(total_price) ~ ., data = train_tb_train_filter[, -2]) %>% 
           predict(., newdata = train_tb_test_filter)) %>% 
  select(total_price_pred, total_price, everything()) %>% 
  mutate(z_score = ifelse((abs(total_price_pred - total_price)/total_price) <= 0.1, 1, 0)) %>% 
  summarise(hit_rate = sum(z_score, na.rm = T)/sum(ifelse(is.na(z_score), 0, 1))) %>% View()
  
```


---

#### 

```{r, eval=FALSE, echo=FALSE}
### test
train %>% 
  distinct(city, town, town_area) %>% View
  group_by(city, town) %>% 
  tally %>% View

## set 18000 = "1950-01-01"
train %>% 
  arrange(txn_dt %>% desc) %>% 
  mutate(tmp_dt = ymd("2000-01-01")+(txn_dt-18000)) %>% head %>% 
  select(1:5, tmp_dt) %>% View
  distinct(city, town_population) %>% View
  
tmp <- fread("/Users/hsiaoling/Documents/Team/資料集/data.csv") %>% select(-1)
tmp %>% 
  group_by(`主要建材`) %>% 
  tally %>% View
```


---

